return {
  [2] = {
    id_mercado = 2,
    comprador = "Kakashi",
    id_item = 826,
    vendedor = "Kakashi",
    quantidade = 1,
    valor_resgate = 0,
    status = "vendido",
    preco = 15,
  },
  [5] = {
    id_mercado = 5,
    id_item = 192,
    vendedor = "Kakashi",
    quantidade = 1,
    status = "ativo",
    preco = 50000,
  },
  [3] = {
    id_mercado = 3,
    comprador = "Kakashi",
    id_item = 826,
    vendedor = "Kakashi",
    quantidade = 1,
    valor_resgate = 0,
    status = "vendido",
    preco = 15,
  },
  [1] = {
    id_mercado = 1,
    comprador = "Kakashi",
    id_item = 825,
    vendedor = "Kakashi",
    quantidade = 1,
    valor_resgate = 0,
    status = "vendido",
    preco = 15,
  },
  [4] = {
    id_mercado = 4,
    comprador = "Hinata",
    id_item = 826,
    vendedor = "Kakashi",
    quantidade = 1,
    status = "vendido",
    valor_resgate = 0,
    preco = 1500,
  },
  [6] = {
    id_mercado = 6,
    comprador = "Kakashi",
    id_item = 192,
    vendedor = "Hinata",
    quantidade = 1,
    valor_resgate = 0,
    status = "vendido",
    preco = 50000,
  },
}